# -*- coding: utf-8 -*-
"""Gabarito - Listas 05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tdmi62RbpfKHAWB_-w3CC8gRDmww6Yar

# Algumas Funções Básicas de Lista

## Tamanho da Lista

tamanho = len(lista)
"""

produtos = ['apple tv', 'mac', 'iphone x', 'IPad', 'apple watch', 'mac book', 'airpods']

"""- Quantos produtos temos a venda?"""

tamanho = len(produtos)
print('Temos {} produtos'.format(tamanho))

"""## Maior e Menor Valor

maior = max(lista)

menor = min(lista)
"""

vendas = [1000, 1500, 15000, 270, 900, 100, 1200]

"""- Qual o item mais vendido?
- Qual o item menos vendido?
"""

mais_vendido = max(vendas)
menos_vendido = min(vendas)
print('O produto mais vendido teve {} unidades vendidas e o menos vendido teve {} unidades vendidas'.format(mais_vendido, menos_vendido))

i = vendas.index(mais_vendido)
produto_mais_vendido = produtos[i]

print(produto_mais_vendido)

i = vendas.index(menos_vendido)
produto_menos_vendido = produtos[i]

print(produto_menos_vendido)